# Based on https://github.com/wp-cli/scaffold-command/blob/f9bad3dd7224d5684d950d31c486df70905e386f/templates/plugin-github.mustache
# Thanks Josh https://github.com/Shelob9/wordpress-plugin/blob/main/.github/workflows/wordpress.yml
# Thanks https://github.com/shivammathur
name: WordPress Tests

on:
  push:
    branches:
      - trunk
      - develop
  pull_request:
    branches:
      - trunk
      - develop

jobs:
  run:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        php-versions: ['7.4', '8.0', '8.1']
        phpunit-versions: ['9.5.20']
        include:
          - php-versions: '5.6'
            phpunit-versions: '5.7.27'
          - php-versions: '7.0'
            phpunit-versions: '5.7.27'
          - php-versions: '7.1'
            phpunit-versions: '7.5.20'
          - php-versions: '7.2'
            phpunit-versions: '7.5.20'
          - php-versions: '7.3'
            phpunit-versions: '9.5.20'
    name: PHP ${{ matrix.php-versions }} Test on ${{ matrix.operating-system }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        coverage: none
        extensions: mysql
        tools: wp-cli, phpunit-polyfills, phpunit:${{ matrix.phpunit-versions }}
      env:
        COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Check PHP Version
      run: php -v

    - name: Composer install
      run: composer install --optimize-autoloader --prefer-dist

    - name: Start Mysql
      run: sudo service mysql start

    - name: Install WP Tests
      run: bash bin/install-wp-tests.sh wordpress_test root root localhost latest

    - name: phpunit tests
      run: |
        echo "define('WP_TESTS_PHPUNIT_POLYFILLS_PATH', '$HOME/.composer/vendor/yoast/phpunit-polyfills');" >> /tmp/wordpress-tests-lib/wp-tests-config.php
        /usr/local/bin/phpunit --config=phpunit.xml
